base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: gkswoghk

development:
  database: ceotalk_development
  <<: *base
xe_development:
  database: drh_ceotalk_board
  <<: *base

test:
  database: ceotalk_test
  <<: *base

production:
  database: ceotalk_production
  <<: *base
